import {
  mdiEraser,
  mdiBrush,
  mdiUndo,
  mdiRedo,
  // mdiSquare,
  mdiVectorCombine,
  mdiPlay,
  mdiStop,
  mdiPause,
  mdiArrowLeft,
  mdiArrowRight,
  mdiPlus,
  mdiContentDuplicate,
  mdiTrashCan,
  mdiMinus,
  mdiRectangleOutline,
  mdiCircleOutline,
  mdiRectangle,
  mdiCircle,
  mdiFormatColorFill,
  mdiContentSave,
  mdiInformation,
  mdiBackspace,
  mdiMerge,
  mdiDotsHorizontal,
  // mdiImage,
  mdiVectorSquareClose,
  mdiSpeedometer,
} from "@mdi/js";

const tools = [
  { icon: mdiBrush, name: "Brush", description: "Draw lines" },
  { icon: mdiEraser, name: "Eraser", description: "Erase lines" },
  { icon: mdiUndo, name: "Undo", description: "Undo last action" },
  { icon: mdiRedo, name: "Redo", description: "Redo last action" },
  // { icon: mdiSquare, name: "Square", description: "Draw square" },
  {
    icon: mdiVectorCombine,
    name: "Onion",
    description: "Set gray prev frames",
  },
  { icon: mdiPlay, name: "Play", description: "Play animation" },
  { icon: mdiStop, name: "Stop", description: "Stop animation" },
  { icon: mdiPause, name: "Pause", description: "Pause animation" },
  { icon: mdiArrowLeft, name: "Left", description: "Move left" },
  { icon: mdiArrowRight, name: "Right", description: "Move to right" },
  { icon: mdiPlus, name: "Plus", description: "Add layer" },
  {
    icon: mdiContentDuplicate,
    name: "Duplicate",
    description: "Duplicate layer",
  },
  { icon: mdiTrashCan, name: "Delete", description: "Delete layer" },
  { icon: mdiMinus, name: "Minus", description: "Remove layer" },
  {
    icon: mdiRectangleOutline,
    name: "Rectangle",
    description: "Draw rectangle",
  },
  { icon: mdiCircleOutline, name: "Circle", description: "Draw circle" },
  { icon: mdiRectangle, name: "Rectangle", description: "Draw rectangle" },
  { icon: mdiCircle, name: "Circle", description: "Draw circle" },
  { icon: mdiFormatColorFill, name: "Fill", description: "Fill color" },
  { icon: mdiContentSave, name: "Save", description: "Save animation" },
  { icon: mdiInformation, name: "Info", description: "Show animation info" },
  {
    icon: mdiBackspace,
    name: "Backspace",
    description: "Empty layer contents",
  },
  { icon: mdiMerge, name: "Merge", description: "Merge layers" },
  // { icon: mdiImage, name: "Image", description: "Upload image" },
  { icon: mdiDotsHorizontal, name: "More", description: "Show more options" },
  { icon: mdiVectorSquareClose, name: "Onion...", description: "idk yet" },
  { icon: mdiSpeedometer, name: "Speed", description: "Change speed" },
];

export default tools;
